import * as THREE from 'three';
import './style.css';
import {stepCar,keepInsideArena,resolveCarCollision,PHYSICS} from '../../shared/physics.js';

const canvas=document.querySelector('#game'),scoreElement=document.querySelector('#score'),overlay=document.querySelector('#overlay'),title=document.querySelector('#overlay-title'),copy=document.querySelector('#overlay-copy'),startButton=document.querySelector('#start-button');
const scene=new THREE.Scene();scene.background=new THREE.Color('#172337');scene.fog=new THREE.Fog('#172337',38,85);
const camera=new THREE.PerspectiveCamera(48,1,.1,120);camera.position.set(0,31,34);camera.lookAt(0,0,0);
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
scene.add(new THREE.HemisphereLight(0xc5e9ff,0x23311e,2));const sun=new THREE.DirectionalLight(0xffffff,3);sun.position.set(-12,24,10);sun.castShadow=true;scene.add(sun);
const floor=new THREE.Mesh(new THREE.CircleGeometry(PHYSICS.arenaRadius,96),new THREE.MeshStandardMaterial({color:'#28434c',roughness:.82}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);
const boundary=new THREE.Mesh(new THREE.TorusGeometry(PHYSICS.arenaRadius-.15,.32,12,128),new THREE.MeshStandardMaterial({color:'#ffae62',emissive:'#662d10',roughness:.4}));boundary.rotation.x=Math.PI/2;boundary.position.y=.18;scene.add(boundary);
const markings=new THREE.Mesh(new THREE.TorusGeometry(16,.045,6,100),new THREE.MeshBasicMaterial({color:'#ffffff',transparent:true,opacity:.24}));markings.rotation.x=Math.PI/2;markings.position.y=.035;scene.add(markings);
function makeCar(color){const group=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(1.8,.8,2.8),new THREE.MeshStandardMaterial({color,roughness:.32,metalness:.08}));body.position.y=.72;body.castShadow=true;body.receiveShadow=true;group.add(body);const cabin=new THREE.Mesh(new THREE.BoxGeometry(1.15,.58,1.15),new THREE.MeshStandardMaterial({color:'#e8f6ff',roughness:.25}));cabin.position.set(0,1.28,-.12);cabin.castShadow=true;group.add(cabin);for(const x of [-.98,.98])for(const z of [-.85,.85]){const wheel=new THREE.Mesh(new THREE.BoxGeometry(.28,.48,.68),new THREE.MeshStandardMaterial({color:'#121821',roughness:.8}));wheel.position.set(x,.43,z);wheel.castShadow=true;group.add(wheel)}const light=new THREE.PointLight(color,2,5);light.position.y=1.2;group.add(light);scene.add(group);return group}
const playerMesh=makeCar('#62e6bd'),enemyMesh=makeCar('#ff7185');
const itemMeshes=[];const itemGeo=new THREE.IcosahedronGeometry(.65,1);const itemMat=new THREE.MeshStandardMaterial({color:'#ffd166',emissive:'#6d4b0a',emissiveIntensity:.8,metalness:.3,roughness:.25});
for(let i=0;i<7;i++){const mesh=new THREE.Mesh(itemGeo,itemMat);mesh.position.y=.8;mesh.castShadow=true;scene.add(mesh);itemMeshes.push(mesh)}
let player,enemy,items,score=0,running=false,last=0,dashCooldown=0,dashTime=0,raf=0;const keys=new Set();
function reset(){score=0;scoreElement.textContent='0';player={x:-8,z:0,angle:Math.PI/2,speed:0};enemy={x:8,z:0,angle:-Math.PI/2,speed:0};const spots=[[-10,-8],[0,10],[12,-5],[6,2],[-4,-13],[-13,6],[13,11]];items=spots.map(([x,z],i)=>({x,z,phase:i*.8,taken:false}));items.forEach((item,i)=>{itemMeshes[i].visible=true;itemMeshes[i].position.set(item.x,.8,item.z)})}
function input(){const up=keys.has('w')||keys.has('arrowup'),down=keys.has('s')||keys.has('arrowdown'),left=keys.has('a')||keys.has('arrowleft'),right=keys.has('d')||keys.has('arrowright');return{throttle:Number(up)-Number(down),steering:Number(right)-Number(left)}}
function updateBot(dt){const dx=player.x-enemy.x,dz=player.z-enemy.z,target=Math.atan2(dx,dz),delta=Math.atan2(Math.sin(target-enemy.angle),Math.cos(target-enemy.angle));enemy=stepCar(enemy,{throttle:.85,steering:THREE.MathUtils.clamp(delta*1.65,-1,1)},dt);enemy=keepInsideArena(enemy);[enemy,player]=resolveCarCollision(enemy,player)}
function update(dt,time){if(!running)return;dashCooldown=Math.max(0,dashCooldown-dt);dashTime=Math.max(0,dashTime-dt);player=stepCar(player,input(),dt);if(keys.has(' ')&&dashCooldown===0){player.speed=Math.min(20,player.speed+7);dashCooldown=1.35;dashTime=.2}player=keepInsideArena(player);updateBot(dt);items.forEach((item,i)=>{const mesh=itemMeshes[i];mesh.rotation.y=time*.0015+item.phase;mesh.position.y=.85+Math.sin(time*.003+item.phase)*.13;if(!item.taken&&Math.hypot(player.x-item.x,player.z-item.z)<1.65){item.taken=true;mesh.visible=false;score++;scoreElement.textContent=String(score)}});if(items.every(i=>i.taken))resetItems();if(Math.hypot(player.x-enemy.x,player.z-enemy.z)<2.2)end()}
function resetItems(){const positions=[[-10,-8],[0,10],[12,-5],[6,2],[-4,-13],[-13,6],[13,11]];items.forEach((item,i)=>{item.x=positions[i][0];item.z=positions[i][1];item.taken=false;itemMeshes[i].visible=true;itemMeshes[i].position.set(item.x,.8,item.z)})}
function syncMeshes(){playerMesh.position.set(player.x,0,player.z);playerMesh.rotation.y=player.angle;enemyMesh.position.set(enemy.x,0,enemy.z);enemyMesh.rotation.y=enemy.angle}
function draw(){renderer.render(scene,camera)}
function frame(time){const dt=Math.min((time-last)/1000||0,.05);last=time;update(dt,time);syncMeshes();camera.position.x+=(player.x*.32-camera.position.x)*.025;camera.position.z+=(34+player.z*.3-camera.position.z)*.025;camera.lookAt(player.x*.22,0,player.z*.22);draw();if(running)raf=requestAnimationFrame(frame)}
function start(){cancelAnimationFrame(raf);reset();running=true;overlay.hidden=true;last=performance.now();raf=requestAnimationFrame(frame)}
function end(){running=false;title.textContent='Tu as été rattrapé !';copy.textContent=`Tu as ramassé ${score} étoile${score===1?'':'s'}. Réessaie pour battre ton record.`;startButton.textContent='Recommencer';overlay.hidden=false}
function resize(){const rect=canvas.getBoundingClientRect();renderer.setSize(rect.width,rect.height,false);camera.aspect=rect.width/rect.height;camera.updateProjectionMatrix();draw()}
startButton.addEventListener('click',start);window.addEventListener('resize',resize);window.addEventListener('keydown',e=>{const key=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(key))e.preventDefault();keys.add(key);if(key==='r')start()});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>keys.clear());resize();reset();syncMeshes();draw();
