// Constantes et opérations de match, communes au client et au serveur.
export const RULES=Object.freeze({matchDuration:180,scoreToWin:10,itemRespawnDelay:5,maxPlayers:2,maxNicknameLength:20});
export const ITEM_TYPES=Object.freeze({boost:Object.freeze({points:1,effect:'boost'}),star:Object.freeze({points:3,effect:'bonus'}),shield:Object.freeze({points:1,effect:'shield'}),magnet:Object.freeze({points:1,effect:'magnet'})});
export function sanitizeInput(input={}){const clamp=v=>Math.max(-1,Math.min(1,v));const num=v=>Number.isFinite(v)?v:0;return{throttle:clamp(num(input.throttle)),steering:clamp(num(input.steering)),handbrake:Boolean(input.handbrake),useItem:Boolean(input.useItem)}}
export function createPlayer(id,nickname,spawn={}){return{id:String(id),nickname:String(nickname??'Joueur').trim().slice(0,RULES.maxNicknameLength)||'Joueur',x:Number.isFinite(spawn.x)?spawn.x:0,z:Number.isFinite(spawn.z)?spawn.z:0,angle:Number.isFinite(spawn.angle)?spawn.angle:0,speed:0,score:0,itemsCollected:0,input:sanitizeInput(),connected:true}}
export function createMatch(id,now=Date.now()){return{id:String(id),status:'waiting',createdAt:now,startedAt:null,endsAt:null,finishedAt:null,winnerId:null,players:[],items:[]}}
export function addPlayer(match,player){if(match.status!=='waiting')return{ok:false,error:'match_already_started'};if(match.players.length>=RULES.maxPlayers)return{ok:false,error:'match_full'};if(match.players.some(p=>p.id===player.id))return{ok:false,error:'player_already_joined'};return{ok:true,match:{...match,players:[...match.players,player]}}}
export function startMatch(match,now=Date.now()){if(match.status!=='waiting'||match.players.length!==RULES.maxPlayers)return{ok:false,error:'match_not_ready'};return{ok:true,match:{...match,status:'playing',startedAt:now,endsAt:now+RULES.matchDuration*1000}}}
export function setPlayerInput(match,playerId,input){if(match.status!=='playing')return match;return{...match,players:match.players.map(p=>p.id===playerId?{...p,input:sanitizeInput(input)}:p)}}
export function collectItem(match,playerId,itemId){if(match.status!=='playing')return{ok:false,error:'match_not_playing'};const item=match.items.find(i=>i.id===itemId&&i.available),player=match.players.find(p=>p.id===playerId);if(!item||!player)return{ok:false,error:'item_or_player_not_found'};const type=ITEM_TYPES[item.type];if(!type)return{ok:false,error:'unknown_item_type'};const next={...match,items:match.items.map(i=>i.id===itemId?{...i,available:false}:i),players:match.players.map(p=>p.id===playerId?{...p,score:p.score+type.points,itemsCollected:p.itemsCollected+1}:p)};return{ok:true,match:next.players.find(p=>p.id===playerId).score>=RULES.scoreToWin?finishMatch(next,playerId):next}}
export function finishMatch(match,winnerId=null,now=Date.now()){if(match.status!=='playing')return match;return{...match,status:'finished',winnerId,finishedAt:now}}
export function updateMatchClock(match,now=Date.now()){if(match.status!=='playing'||now<match.endsAt)return match;const[a,b]=match.players;return finishMatch(match,a.score===b.score?null:a.score>b.score?a.id:b.id,now)}
